version: '3.5'  

services:
    docker-backend: 
      build: ./backend
      volumes:
        - ./backend/logs.txt:/app/backend-example-docker/logs.txt
      ports: 
        - 8000:8000

    docker-frontend: 
      build: ./frontend
      ports: 
        - 5000:5000

